# Generated by Django 4.0.2 on 2022-02-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoreview',
            old_name='like',
            new_name='likes',
        ),
    ]
